version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - jenkins
    volumes:
      - ../var/jenkins_home:/var/jenkins_home
      - ../var/run/docker.sock:/var/run/docker.sock
  postgres:
    image: postgres:9.6
    networks:
      - jenkins
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonarpasswd
    volumes:
      - ../var/postgres-data:/var/lib/postgresql/data
  sonarqube:
    image: sonarqube:5.6.6
    ports:
      - "9000:9000"
      - "9092:9092"
      - "5432:5432"
    networks:
      - jenkins
    environment:
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonarpasswd
      SONARQUBE_JDBC_URL: "jdbc:postgresql://postgres:5432/sonar"
    volumes:
      - ../opt/sonarqube/data:/opt/sonarqube/data
      - ../opt/sonarqube/logs:/opt/sonarqube/logs
      - ../opt/sonarqube/extensions:/opt/sonarqube/extensions
    depends_on: 
      - postgres

networks:
  jenkins: